Importar librerias

In [1]:
import pandas as pd
import numpy as np

Importar datos del berlin32.txt a una matriz

In [2]:
berlin52 = pd.read_csv("berlin32.txt", header=None, skiprows=6, skipfooter=1, engine='python', delim_whitespace=True, usecols=(1,2), dtype=int)

matrizBerlin52 = berlin52.to_numpy() 

numVariables = matrizBerlin52.shape[0] #52

print('Matriz:\n', matrizBerlin52,'\nNumero de variables: ', numVariables)

Matriz:
 [[ 565  575]
 [  25  185]
 [ 345  750]
 [ 945  685]
 [ 845  655]
 [ 880  660]
 [  25  230]
 [ 525 1000]
 [ 580 1175]
 [ 650 1130]
 [1605  620]
 [1220  580]
 [1465  200]
 [1530    5]
 [ 845  680]
 [ 725  370]
 [ 145  665]
 [ 415  635]
 [ 510  875]
 [ 560  365]
 [ 300  465]
 [ 520  585]
 [ 480  415]
 [ 835  625]
 [ 975  580]
 [1215  245]
 [1320  315]
 [1250  400]
 [ 660  180]
 [ 410  250]
 [ 420  555]
 [ 575  665]
 [1150 1160]
 [ 700  580]
 [ 685  595]
 [ 685  610]
 [ 770  610]
 [ 795  645]
 [ 720  635]
 [ 760  650]
 [ 475  960]
 [  95  260]
 [ 875  920]
 [ 700  500]
 [ 555  815]
 [ 830  485]
 [1170   65]
 [ 830  610]
 [ 605  625]
 [ 595  360]
 [1340  725]
 [1740  245]] 
Numero de variables:  52


Crear matriz de distancias a partir de la matriz anterior

In [3]:
matrizDistancias = np.full((numVariables,numVariables), fill_value=-1.0, dtype=float)

for i in range(numVariables-1):
    for j in range(i+1, numVariables):
        distancia = np.sqrt(np.sum(np.square(matrizBerlin52[i]-matrizBerlin52[j]))) #Se llena la matriz de distancias utilizando los valores de la matrizBerlin32, utilizando la formula de distancia
        matrizDistancias[i][j] = distancia
        matrizDistancias[j][i] = distancia

print('Matriz de Distancias:\n',matrizDistancias)

Matriz de Distancias:
 [[-1.00000000e+00  6.66108099e+02  2.81113856e+02 ...  2.17082933e+02
   7.89382670e+02  1.22046098e+03]
 [ 6.66108099e+02 -1.00000000e+00  6.49326574e+02 ...  5.96259172e+02
   1.42155724e+03  1.71604924e+03]
 [ 2.81113856e+02  6.49326574e+02 -1.00000000e+00 ...  4.63249393e+02
   9.95314021e+02  1.48359361e+03]
 ...
 [ 2.17082933e+02  5.96259172e+02  4.63249393e+02 ... -1.00000000e+00
   8.29608341e+02  1.15076062e+03]
 [ 7.89382670e+02  1.42155724e+03  9.95314021e+02 ...  8.29608341e+02
  -1.00000000e+00  6.24819974e+02]
 [ 1.22046098e+03  1.71604924e+03  1.48359361e+03 ...  1.15076062e+03
   6.24819974e+02 -1.00000000e+00]]


Crear matriz de heuristicas a partir de la matriz anterior

In [4]:
matrizHeuristicas = np.full_like(matrizDistancias, fill_value=(1/matrizDistancias), dtype=float) #Se llena la matriz de heuristicas con 1 dividido lo que haya en cada posicion de matrizDistancias  
np.fill_diagonal(matrizHeuristicas, 0.0) #Esto se hace para llenar de 0s la diagonal de la matriz 

print('Matriz de Heuristicas:\n',matrizHeuristicas)

Matriz de Heuristicas:
 [[0.         0.00150126 0.00355728 ... 0.00460653 0.00126681 0.00081936]
 [0.00150126 0.         0.00154006 ... 0.00167712 0.00070345 0.00058273]
 [0.00355728 0.00154006 0.         ... 0.00215866 0.00100471 0.00067404]
 ...
 [0.00460653 0.00167712 0.00215866 ... 0.         0.00120539 0.00086899]
 [0.00126681 0.00070345 0.00100471 ... 0.00120539 0.         0.00160046]
 [0.00081936 0.00058273 0.00067404 ... 0.00086899 0.00160046 0.        ]]


Se crea la función que calculará el costo 

In [5]:
def solucionCalcularCosto(cantNodos,matrizSolucion,matrizBase):
    aux = matrizBase[matrizSolucion[cantNodos-1]][matrizSolucion[0]]
    for i in range(cantNodos-1):
        aux += (matrizBase[matrizSolucion[i]][matrizSolucion[i+1]])
    return aux

In [6]:
mejorSolucion = np.arange(0,numVariables)
np.random.shuffle(mejorSolucion)
solucionMejorCosto = solucionCalcularCosto(numVariables,mejorSolucion,matrizHeuristicas)

print(solucionMejorCosto)

0.16878624109718665


In [7]:
def obtenerMatrizFeromonas(matriz,numVar,mejorCosto):
    feromona = np.full_like(matriz, 1/(mejorCosto*numVar))

    return feromona

In [8]:
obtenerMatrizFeromonas(matrizHeuristicas,numVariables,solucionMejorCosto)

(array([[0.11393564, 0.11393564, 0.11393564, ..., 0.11393564, 0.11393564,
         0.11393564],
        [0.11393564, 0.11393564, 0.11393564, ..., 0.11393564, 0.11393564,
         0.11393564],
        [0.11393564, 0.11393564, 0.11393564, ..., 0.11393564, 0.11393564,
         0.11393564],
        ...,
        [0.11393564, 0.11393564, 0.11393564, ..., 0.11393564, 0.11393564,
         0.11393564],
        [0.11393564, 0.11393564, 0.11393564, ..., 0.11393564, 0.11393564,
         0.11393564],
        [0.11393564, 0.11393564, 0.11393564, ..., 0.11393564, 0.11393564,
         0.11393564]]),
 8.776884537053705)

In [9]:
def inicializarHormigas(hormiga, nodos):
    poblacion = np.full((hormiga, nodos), -1)
    for i in range(hormiga):
        poblacion[i][0] = float(np.random.randint(nodos))
    return poblacion

In [10]:
def seleccionar_nuevo_segmento(nodos,tamañoPobl,pobl,feromona,feromLocal,prob_max,matrizDistancias,valor_heur,evap_ferom):
    matrizNodos = np.arange(nodos)
    for i in range(tamañoPobl):
        row = pobl[i][:]
        nodosVisitados = np.where(row != -1)
        nodosVisitados = [pobl[i][item] for item in nodosVisitados]
        nodosNoVisitados = [item for item in matrizNodos if item not in nodosVisitados[0]]
        if np.random.rand() < prob_max:
            arg = []
            for j in nodosNoVisitados:
                arg.append(feromona[nodosVisitados[0][-1]][j]*((matrizDistancias[nodosVisitados[0][-1]][j])**valor_heur))
            arg = np.array(arg)
            max = np.where(arg == np.amax(arg))
            pobl[i][len(nodosVisitados[0])] = nodosNoVisitados[max[0][0]]
            feromona[pobl[i][len(nodosVisitados[0])]][pobl[i][len(nodosVisitados[0])-1]] = (1-evap_ferom)*feromona[pobl[i][len(nodosVisitados[0])]][pobl[i][len(nodosVisitados[0])-1]] + evap_ferom/(nodos*feromLocal)
            feromona[pobl[i][len(nodosVisitados[0])-1]][pobl[i][len(nodosVisitados[0])]] = feromona[pobl[i][len(nodosVisitados[0])]][pobl[i][len(nodosVisitados[0])-1]]
        else:
            arg = [0]
            for j in range(len(nodosNoVisitados)):
                arg.append(feromona[nodosVisitados[0][-1]][nodosNoVisitados[j]]*((matrizDistancias[nodosVisitados[0][-1]][nodosNoVisitados[j]])**valor_heur))
            arg /= np.sum(arg)
            arg = np.array(arg)
            arg = np.cumsum(arg)
            rand = np.random.rand()
            pos = np.where(arg < rand)
            pobl[i][len(nodosVisitados[0])] = nodosNoVisitados[pos[0][-1]]
            feromona[pobl[i][len(nodosVisitados[0])]][pobl[i][len(nodosVisitados[0])-1]] = (1-evap_ferom)*feromona[pobl[i][len(nodosVisitados[0])]][pobl[i][len(nodosVisitados[0])-1]] + evap_ferom/(nodos*feromLocal)
            feromona[pobl[i][len(nodosVisitados[0])-1]][pobl[i][len(nodosVisitados[0])]] = feromona[pobl[i][len(nodosVisitados[0])]][pobl[i][len(nodosVisitados[0])-1]]
    return pobl